from app.models.usuario import Usuario
from app.models.instructor import Instructor
from app.models.area import AreaHidroponia
from app.models.curso import Curso
from app.models.modulo import Modulo
from app.models.leccion import Leccion
from app.models.recurso import RecursoLeccion
from app.models.inscripcion import Inscripcion
from app.models.progreso import ProgresoLeccion
from app.models.calificacion import Calificacion
from app.models.mensaje import ComentarioMensaje